Base:
  Version: v1.0
  RunMode: debug
  HTTPPort: 8888
  ReadTimeout:  100
  WriteTimeout: 100
  PageSize: 10
  JwtSecret:  default
  CpuMaxProcess: -1
Db:
  DriverName: mysql
  #user=postgres password=1qaz2wsx dbname=postgres host=10.168.1.164 port=5432 sslmode=disable
  DBUrl:

Redis:
  RedisHost: 192.168.100.24:6379
  RedisDB: 5
  RedisPwd: 123456
  Timeout: 20
  PoolMaxIdle: 10
  PoolMaxActive: 1
  PoolIdleTimeout: 5
  PoolWait: true
