package participle

const (
	POS_AG string = "ag"
	POS_A  string = "a"
	POS_AD string = "ad"
	POS_AN string = "an"
	POS_B  string = "b"
	POS_C  string = "c"
	POS_DG string = "dg"
	POS_D  string = "d"
	POS_E  string = "e"
	POS_F  string = "f"
	POS_G  string = "g"
	POS_H  string = "h"
	POS_I  string = "i"
	POS_J  string = "j"
	POS_K  string = "k"
	POS_L  string = "l"
	POS_M  string = "m"
	POS_NG string = "Ng"
	POS_N  string = "n"
	POS_NR string = "nr"
	POS_NS string = "ns"
	POS_NT string = "nt"
	POS_NZ string = "nz"
	POS_O  string = "o"
	POS_P  string = "p"
	POS_Q  string = "q"
	POS_R  string = "r"
	POS_S  string = "s"
	POS_TG string = "tg"
	POS_T  string = "t"
	POS_U  string = "u"
	POS_VG string = "vg"
	POS_V  string = "v"
	POS_VD string = "vd"
	POS_VN string = "vn"
	POS_W  string = "w"
	POS_X  string = "x"
	POS_Y  string = "y"
	POS_Z  string = "z"
	POS_UN string = "un"
)
